version: '3.8'

services:
  rstudio:
    image: tschaffter/rstudio:0.2.0
    env_file:
      .env
    restart: always
    volumes:
      - data:/data
      - /home/tschaffter/dev/challenge-analytics:/home/${USER}/project
    ports:
      - "8787:8787"

volumes:
    data: